version: "3.9"
services:
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./data/cassandra_data:/var/lib/cassandra
    networks:
      - backend
networks:
  backend: